workflows:
  - id: W_kwDOLkC0eM4KBwzG
    repo: dhth/act3
    name: main
  - id: W_kwDON4qJ1M4KCoE2
    repo: dhth/bmm
    name: main
  - id: W_kwDOOk2Ess4JuT87
    repo: dhth/chronotes
    name: main
  - id: W_kwDOLb3Pms4KCl62
    repo: dhth/cueitup
    name: main
  - id: W_kwDOOChY484KBxQT
    repo: dhth/ecscope
    name: main
  - id: W_kwDOLghtl84KC1bd
    repo: dhth/ecsv
    name: main
  - id: W_kwDOOh1Jh84JuDWJ
    repo: dhth/ghx
    name: main
  - id: W_kwDOMG_5As4KC5fd
    repo: dhth/hours
    name: main
  - id: W_kwDOLa0twM4KClii
    repo: dhth/kplay
    name: main
  - id: W_kwDOOu3ogM4KBjiY
    repo: dhth/mrj
    name: main
  - id: W_kwDON18Fhs4KByGh
    repo: dhth/tash
    name: main
  - id: W_kwDOMnT5Os4KCzgp
    repo: dhth/tbll
    name: main
