# the list of workflows you want results for
workflows:

  # the workflow's node_id
  # You can find the it as follows:
  # 
  # ```bash
  # curl -L \
  #   -H "Accept: application/vnd.github+json" \
  #   -H "Authorization: Bearer <GH_TOKEN>" \
  #   -H "X-GitHub-Api-Version: 2022-11-28" \
  #   https://api.github.com/repos/<OWNER>/<REPO>/actions/workflows
  # 
  # or
  # 
  # gh api repos/<OWNER>/<REPO>/actions/workflows
  - id: W_kwDOLkC0eM4KBwzG

    # this will show up in the results
    repo: dhth/act3

    # this will show up in the results
    name: main

    # (optional) if set, will be used instead of the repo and the workflow name
    key: bloopy

    # (optional) if set, will be used as the link to a workflow run instead of
    # the GitHub URL
    # {{runNumber}} gets replaced with the actual run number of the workflow.
    url: https://asampleurl.com/{{runNumber}}

  - id: W_kwDON4qJ1M4KCoE2"
    repo: dhth/bmm
    name: main

  - id: W_kwDOMG_5As4KC5fd
    repo: dhth/hours
    name: main
