name: deploy-docs

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  GO_VERSION: 1.24.3
  TAILWIND_VERSION: 4.1.6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tailwind
        run: |
          curl \
            -sSL \
            -o tailwindcss \
            https://github.com/tailwindlabs/tailwindcss/releases/download/v${{ env.TAILWIND_VERSION }}/tailwindcss-linux-x64-musl
          chmod +x ./tailwindcss
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install act3
        run: go install .
      - name: Generate GH token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_TOKEN_APP_ID }}
          private-key: ${{ secrets.GH_TOKEN_APP_PRIVATE_KEY }}
      - name: Generate doc
        run: |
          act3 \
            -r neovim/neovim \
            -t .github/showcase/template.html \
            -f html > .github/showcase/assets/index.html
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Generate css
        run: |
          ./tailwindcss \
            -i .github/showcase/assets/index.css \
            -o .github/showcase/assets/act3.css \
      - name: Copy assets to dist
        run: |
          mkdir -p dist
          cp .github/showcase/assets/{index.html,favicon.png,act3.css} dist
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
