name: Deploy Docs

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: go build -v ./...
    - name: Generate doc
      run: |
        ./act3 \
          -config-file=./docs/act3.yml \
          -format=html \
          -html-template-file=./docs/template.html > ./docs/index.html
      env:
        ACT3_GH_ACCESS_TOKEN: ${{secrets.ACT3_GH_ACCESS_TOKEN}}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
