name: run

on:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  GO_VERSION: '1.24.3'

jobs:
  run:
    name: test-run
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: go build
        run: go build .
      - name: Generate GH token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_TOKEN_APP_ID }}
          private-key: ${{ secrets.GH_TOKEN_APP_PRIVATE_KEY }}
      - name: Run act3 with default output
        run: ./act3
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Run act3 with tabular output
        run: ./act3 -f table
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Run act3 with HTML output
        run: ./act3 -f html
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
